### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by kaiser-ok** [QuentinFuxa/whisper_streaming_web#3]
While recording, I meet this issue.. 
  File "/Downloads/code/whisper/whisper_streaming_web/whisper_fastapi_online_server.py", line 65, in websocket_endpoint
    ffmpeg_process = await start_ffmpeg_decoder()
  File "/Downloads/code/whisper/whisper_streaming_web/whisper_fastapi_online_server.py", line 54, in start_ffmpeg_decoder
    .input('pipe:0', format='webm')
    
 AttributeError: module 'ffmpeg' has no attribute 'input'
INFO:     connection open
INFO:     connection closed
^CINFO:     Shutting down  
    
Could you help me?

% pip show ffmpeg   
Name: ffmpeg
Version: 1.4
Summary: ffmpeg python package url [https://github.com/jiashaokun/ffmpeg]
Home-page: https://github.com/jiashaokun/ffmpeg
Author: SkeyJIA
Author-email: 363604236@qq.com
License: MIT Licence
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Requires: 
Required-by: 

% python3 ./whisper_fastapi_online_server.py --host 0.0.0.0 --port 8000 --backend mlx-whisper  --vad  --min-chunk-size 1000

**Comment by rupnil-codes** [comment]
```
pip uninstall ffmeg
pip install ffmpeg-python
```

**Comment by QuentinFuxa** [comment]
Thank you @rupnil-codes for pointing this out. I will update the README to indicate the correct required library 👍

**Comment by rupnil-codes** [comment]
@QuentinFuxa You could add a requirements.txt. I can make a pull req for adding the requirements.txt if u want

**Comment by QuentinFuxa** [comment]
I prefer to keep the requirements in the README for now, as some of them are mandatory, some are optional, and for some, you need to choose at least one from a list of options (the whisper backends)

But thank you :)

**Comment by rupnil-codes** [comment]
> I prefer to keep the requirements in the README for now, as some of them are mandatory, some are optional, and for some, you need to choose at least one from a list of options (the whisper backends)
> 
> But thank you :)

Ya all good, btw have u looked into the VACOnlineASRProcessor? and my suggestion of picovoice Cobra VAD

**Comment by QuentinFuxa** [comment]
> I prefer to keep the requirements in the README for now, as some of them are mandatory, some are optional, and for some, you need to choose at least one from a list of options (the whisper backends)
> But thank you :)

I am looking into the VACOnlineASRProcessor issue, I will let you know when it is done.

However, I don't think I will work on an implementation of picovoice Cobra VAD, since the goal of this repository is to have a free, MIT-licensed, local and open source tool, which is not the case of picovoice Cobra VAD. However, feel free to work on a fork that implements it, and I can reference it here if you want

**Comment by rupnil-codes** [comment]
> > I prefer to keep the requirements in the README for now, as some of them are mandatory, some are optional, and for some, you need to choose at least one from a list of options (the whisper backends)
> > But thank you :)
> 
> I am looking into the VACOnlineASRProcessor issue, I will let you know when it is done.
> 
> However, I don't think I will work on an implementation of picovoice Cobra VAD, since the goal of this repository is to have a free, MIT-licensed, local and open source tool, which is not the case of picovoice Cobra VAD. However, feel free to work on a fork that implements it, and I can reference it here if you want

Yep! all good. Btw should I make a pull request for the added support of a terminal app? Or create a fork that u can reference?

**Comment by QuentinFuxa** [comment]
The https://github.com/ufal/whisper_streaming project, which mine is based on, already includes support for a terminal app. I’d recommend taking a look at their implementation. If you see any areas for improvement, you could consider contributing by making a pull request directly to their repository. Let me know if I can assist in any way!

**Comment by rupnil-codes** [comment]
@QuentinFuxa Just fixing the VAC process would be the most important thing rn.

Thanks
