### ISSUE TITLE
Exception in ffmpeg_stdout_reader: 'MosesTokenizer' object has no attribute 'split'

### ISSUE THREAD

**Issue by SilasK** [QuentinFuxa/whisper_streaming_web#7]
I get it running for some secconds. but then got. 

I use ffmpeg-python = ">=0.2.0,<0.3
mosestokenizer  1.0.0"

Exception in ffmpeg_stdout_reader: 'MosesTokenizer' object has no attribute 'split'
Exiting ffmpeg_stdout_reader...

without  --buffer_trimming sentence

it works

**Comment by SilasK** [comment]
the error comes from whisper_online.py L574

**Comment by SilasK** [comment]
In this context I also wanted to mention that concatenate with a space might not be the solution for everithing. e.g. in frech we have often words after appostrophes which get splited by whisper. but no space is probably worse..

**Comment by QuentinFuxa** [comment]
Solved in https://github.com/QuentinFuxa/whisper_streaming_web/pull/10
