### ISSUE TITLE
Model is downloaded only after reccording 

### ISSUE THREAD

**Issue by SilasK** [QuentinFuxa/whisper_streaming_web#8]
even if I specified a warmup file. 

This should ideally be run at the init of the app. and mentioned on the webpage.

**Comment by SilasK** [comment]
But this is only a detail. 

Great Job!

**Comment by QuentinFuxa** [comment]
Hi @SilasK 
The model is downloaded only on the first run, and is then stored in the cache directory. You can change this cache dir using `--model_cache_dir` parameter

**Comment by SilasK** [comment]
Yes, I know. it is just bad for the demo effect if the browser writes recording... but in the backend you need to download the model for ~5min. which gives the impression that it is much slower than it is. 

The model could be downloaded on loading the page. and ideally one could ad the warmup using a file or so..

**Comment by QuentinFuxa** [comment]
Hi, yes. I solved this in the last commit. Frontend does not allow recording if connection to websocket is not opened, and websocket connection is opened only once the model is downloaded and loaded.

**Comment by QuentinFuxa** [comment]
![image](https://github.com/user-attachments/assets/20183683-a86d-4f1f-83ca-b8dea0b38b80)
