### ISSUE TITLE
uncomitted text stays after a pause

### ISSUE THREAD

**Issue by SilasK** [QuentinFuxa/whisper_streaming_web#9]
using vad (and sentence trimming).

After stoping speaking I get often that the last
last gray text stays even if the same text is already commited (black). This leads to a duplication of the text.

**Comment by QuentinFuxa** [comment]
Hey @SilasK, 
This should have been corrected in the latest commit 2 hours ago. (https://github.com/QuentinFuxa/whisper_streaming_web/commit/b971ca3840544b8574e38c3a594fd960218492da). Can you pull and retry ?

**Comment by QuentinFuxa** [comment]
Solved in https://github.com/QuentinFuxa/whisper_streaming_web/commit/b971ca3840544b8574e38c3a594fd960218492da
